use derivative::Derivative;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Derivative)]
#[derivative(Default)]
pub struct NK1 {
    pub nk1_1_set_id: String,
    pub nk1_2_name: Option<Vec<String>>,
    pub nk1_3_relationship: Option<String>,
    pub nk1_4_address: Option<Vec<String>>,
    pub nk1_5_phone_number: Option<Vec<String>>,
    pub nk1_6_business_phone_number: Option<Vec<String>>,
    pub nk1_7_contact_role: Option<String>,
    pub nk1_8_start_date: Option<String>,
    pub nk1_9_end_date: Option<String>,
    pub nk1_10_next_of_kin_associated_parties_job_title: Option<String>,
    pub nk1_11_next_of_kin_associated_parties_job_code_class: Option<String>,
    pub nk1_12_next_of_kin_associated_parties_employee_number: Option<String>,
    pub nk1_13_organization_name_nk1: Option<Vec<String>>,
    pub nk1_14_marital_status: Option<String>,
    pub nk1_15_administrative_sex: Option<String>,
    pub nk1_16_date_time_of_birth: Option<String>,
    pub nk1_17_living_dependency: Option<Vec<String>>,
    pub nk1_18_ambulatory_status: Option<Vec<String>>,
    pub nk1_19_citizenship: Option<Vec<String>>,
    pub nk1_20_primary_language: Option<String>,
    pub nk1_21_living_arrangement: Option<String>,
    pub nk1_22_publicity_code: Option<String>,
    pub nk1_23_protection_indicator: Option<String>,
    pub nk1_24_student_indicator: Option<String>,
    pub nk1_25_religion: Option<String>,
    pub nk1_26_mothers_maiden_name: Option<Vec<String>>,
    pub nk1_27_nationality: Option<String>,
    pub nk1_28_ethnic_group: Option<Vec<String>>,
    pub nk1_29_contact_reason: Option<Vec<String>>,
    pub nk1_30_contact_persons_name: Option<Vec<String>>,
    pub nk1_31_contact_persons_telephone_number: Option<Vec<String>>,
    pub nk1_32_contact_persons_address: Option<Vec<String>>,
    pub nk1_33_next_of_kin_associated_partys_identifiers: Option<Vec<String>>,
    pub nk1_34_job_status: Option<String>,
    pub nk1_35_race: Option<Vec<String>>,
    pub nk1_36_handicap: Option<String>,
    pub nk1_37_contact_person_social_security_number: Option<String>,
    pub nk1_38_next_of_kin_birth_place: Option<String>,
    pub nk1_39_vip_indicator: Option<String>,
    pub nk1_40_next_of_kin_telecommunication_information: Option<String>,
    pub nk1_41_contact_persons_telecommunication_information: Option<String>,
}
